name: Add User
 
on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Key card'
        required: true
      type:
        description: 'Insert or Delete'
        required: true
      area:
        description: 'Wich area'
        required: true
      user:
        description: 'What I have to add'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run:  python3 main.py ${{ github.event.inputs.type}} ${{ github.event.inputs.area}} ${{ github.event.inputs.user}} 

      - name: commit changed file
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git branch add-new-user
          git switch add-new-user
          git pull origin add-new-user
          git add .
          git commit -m "DAT-${{ github.event.inputs.key}} - Add user ${{ github.event.inputs.user}} - GitHub Actions"
          git push --set-upstream origin add-new-user
          git switch master
          git branch -d add-new-user
      

