name: Add User
 
on:
  workflow_dispatch:
    inputs:
      key:
        description: 'Key card'
        required: true
      type:
        description: 'Insert or Delete'
        required: true
      area:
        description: 'Wich area'
        required: true
      user:
        description: 'What I have to add'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # checkout the repository content

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create and pull branch
        run: |
          git config --global user.name 'Juliasse'
          git config --global user.email 'vinicius.dantas@raizen.com'
          git checkout -b add-new-user-${{ github.event.inputs.user}}

      - name: Execute py script # run main.py
        run:  python3 main.py ${{ github.event.inputs.type}} ${{ github.event.inputs.area}} ${{ github.event.inputs.user}} 

      - name: Commit changed file
        run: |
          git add .
          git commit -m "DAT-${{ github.event.inputs.key}} - Add user ${{ github.event.inputs.user}} - GitHub Actions"
          git push --set-upstream origin add-new-user-${{ github.event.inputs.user}}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add user ${{ github.event.inputs.user }}"
          title: "DAT-${{ github.event.inputs.key}} - Add user ${{ github.event.inputs.user}}"
          body: "This Pull Request adds a new user."
          branch: add-new-user-${{ github.event.inputs.user}}
      

